### ISSUE TITLE
请问如何安装使用？

### ISSUE THREAD

**Issue by frankiegu** [cdcchain/cdc-core#2]
如题

**Comment by cdcchain** [comment]
非常感谢您的关注。
本工程暂时还无法Build，后续会逐步发布构建工程的相关文档。

**Comment by cdcchain** [comment]
@frankiegu  已经可以构建了，可以试试

**Comment by DreamerZhang11** [comment]
你好，博主，我是该项目的原作者，因涉及甲方隐私。这个项目我必须删除。希望您能在github上撤销改项目，感激不尽。(可以联系我，邮箱是：zhangfuliang11@163.com   )
